# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
    - ./Users/miriah.peterson@getweave.com/code/go/src/github.com/Soypete/example_grpc_k8s/init:/docker-entrypoint-initdb.d/init.sql
    ports:
    - 5432:5432

volumes:
    postgresql:      
