// Code generated by protoc-gen-go. DO NOT EDIT.
// source: real_estate.proto

package realestate

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Parameters struct {
	MaxPrice             int32    `protobuf:"varint,2,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	NumberOfBedrooms     int32    `protobuf:"varint,4,opt,name=number_of_bedrooms,json=numberOfBedrooms,proto3" json:"number_of_bedrooms,omitempty"`
	NumberOfBathrooms    int32    `protobuf:"varint,5,opt,name=number_of_bathrooms,json=numberOfBathrooms,proto3" json:"number_of_bathrooms,omitempty"`
	LotSize              int32    `protobuf:"varint,6,opt,name=lot_size,json=lotSize,proto3" json:"lot_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameters) Reset()         { *m = Parameters{} }
func (m *Parameters) String() string { return proto.CompactTextString(m) }
func (*Parameters) ProtoMessage()    {}
func (*Parameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f4b6a0fe19ec2, []int{0}
}

func (m *Parameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameters.Unmarshal(m, b)
}
func (m *Parameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameters.Marshal(b, m, deterministic)
}
func (m *Parameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameters.Merge(m, src)
}
func (m *Parameters) XXX_Size() int {
	return xxx_messageInfo_Parameters.Size(m)
}
func (m *Parameters) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameters.DiscardUnknown(m)
}

var xxx_messageInfo_Parameters proto.InternalMessageInfo

func (m *Parameters) GetMaxPrice() int32 {
	if m != nil {
		return m.MaxPrice
	}
	return 0
}

func (m *Parameters) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Parameters) GetNumberOfBedrooms() int32 {
	if m != nil {
		return m.NumberOfBedrooms
	}
	return 0
}

func (m *Parameters) GetNumberOfBathrooms() int32 {
	if m != nil {
		return m.NumberOfBathrooms
	}
	return 0
}

func (m *Parameters) GetLotSize() int32 {
	if m != nil {
		return m.LotSize
	}
	return 0
}

type Location struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,3,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f4b6a0fe19ec2, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Location) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type House struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Price                int32    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	DaysOnMarket         int32    `protobuf:"varint,3,opt,name=days_on_market,json=daysOnMarket,proto3" json:"days_on_market,omitempty"`
	LotSize              int32    `protobuf:"varint,4,opt,name=lot_size,json=lotSize,proto3" json:"lot_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *House) Reset()         { *m = House{} }
func (m *House) String() string { return proto.CompactTextString(m) }
func (*House) ProtoMessage()    {}
func (*House) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f4b6a0fe19ec2, []int{2}
}

func (m *House) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_House.Unmarshal(m, b)
}
func (m *House) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_House.Marshal(b, m, deterministic)
}
func (m *House) XXX_Merge(src proto.Message) {
	xxx_messageInfo_House.Merge(m, src)
}
func (m *House) XXX_Size() int {
	return xxx_messageInfo_House.Size(m)
}
func (m *House) XXX_DiscardUnknown() {
	xxx_messageInfo_House.DiscardUnknown(m)
}

var xxx_messageInfo_House proto.InternalMessageInfo

func (m *House) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *House) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *House) GetDaysOnMarket() int32 {
	if m != nil {
		return m.DaysOnMarket
	}
	return 0
}

func (m *House) GetLotSize() int32 {
	if m != nil {
		return m.LotSize
	}
	return 0
}

type Address struct {
	Street               string    `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	Location             *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f4b6a0fe19ec2, []int{3}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Address) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Results struct {
	Houses               []*House `protobuf:"bytes,1,rep,name=houses,proto3" json:"houses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Results) Reset()         { *m = Results{} }
func (m *Results) String() string { return proto.CompactTextString(m) }
func (*Results) ProtoMessage()    {}
func (*Results) Descriptor() ([]byte, []int) {
	return fileDescriptor_de4f4b6a0fe19ec2, []int{4}
}

func (m *Results) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Results.Unmarshal(m, b)
}
func (m *Results) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Results.Marshal(b, m, deterministic)
}
func (m *Results) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Results.Merge(m, src)
}
func (m *Results) XXX_Size() int {
	return xxx_messageInfo_Results.Size(m)
}
func (m *Results) XXX_DiscardUnknown() {
	xxx_messageInfo_Results.DiscardUnknown(m)
}

var xxx_messageInfo_Results proto.InternalMessageInfo

func (m *Results) GetHouses() []*House {
	if m != nil {
		return m.Houses
	}
	return nil
}

func init() {
	proto.RegisterType((*Parameters)(nil), "RealEstate.Parameters")
	proto.RegisterType((*Location)(nil), "RealEstate.Location")
	proto.RegisterType((*House)(nil), "RealEstate.House")
	proto.RegisterType((*Address)(nil), "RealEstate.Address")
	proto.RegisterType((*Results)(nil), "RealEstate.Results")
}

func init() { proto.RegisterFile("real_estate.proto", fileDescriptor_de4f4b6a0fe19ec2) }

var fileDescriptor_de4f4b6a0fe19ec2 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x41, 0xaf, 0xd2, 0x40,
	0x10, 0xc7, 0xad, 0xd0, 0x96, 0x0e, 0x2f, 0xe6, 0x31, 0xef, 0xe5, 0xa5, 0xea, 0xe5, 0xa5, 0xf1,
	0x80, 0x89, 0x36, 0xa6, 0x7a, 0xf2, 0x26, 0x89, 0x84, 0x83, 0x06, 0xb2, 0xdc, 0xbc, 0x34, 0x0b,
	0x1d, 0xa4, 0xb1, 0xed, 0x92, 0xdd, 0x25, 0x01, 0xbe, 0x83, 0xdf, 0xc6, 0x0f, 0x68, 0x76, 0xb7,
	0x40, 0xb9, 0xed, 0xcc, 0xfc, 0xa7, 0xd3, 0xdf, 0x3f, 0x7f, 0x18, 0x49, 0xe2, 0x55, 0x4e, 0x4a,
	0x73, 0x4d, 0xe9, 0x4e, 0x0a, 0x2d, 0x10, 0x18, 0xf1, 0xea, 0xbb, 0xed, 0x24, 0xff, 0x3c, 0x80,
	0x05, 0x97, 0xbc, 0x26, 0x4d, 0x52, 0xe1, 0x5b, 0x88, 0x6a, 0x7e, 0xc8, 0x77, 0xb2, 0x5c, 0x53,
	0xfc, 0xf2, 0xd9, 0x1b, 0xfb, 0x6c, 0x50, 0xf3, 0xc3, 0xc2, 0xd4, 0x78, 0x0f, 0x3d, 0xfe, 0x9b,
	0xe2, 0x9e, 0x6d, 0x9b, 0x27, 0x7e, 0x00, 0x6c, 0xf6, 0xf5, 0x8a, 0x64, 0x2e, 0x36, 0xf9, 0x8a,
	0x0a, 0x29, 0x44, 0xad, 0xe2, 0xbe, 0x15, 0xdc, 0xbb, 0xc9, 0x7c, 0x33, 0x69, 0xfb, 0x98, 0xc2,
	0x43, 0x47, 0xcd, 0xf5, 0xd6, 0xc9, 0x7d, 0x2b, 0x1f, 0x5d, 0xe4, 0xe7, 0x01, 0xbe, 0x86, 0x41,
	0x25, 0x74, 0xae, 0xca, 0x13, 0xc5, 0x81, 0x15, 0x85, 0x95, 0xd0, 0xcb, 0xf2, 0x44, 0xc9, 0x14,
	0x06, 0x3f, 0xc4, 0x9a, 0xeb, 0x52, 0x34, 0x88, 0xd0, 0x5f, 0x97, 0xfa, 0x18, 0x7b, 0xcf, 0xde,
	0x38, 0x62, 0xf6, 0x8d, 0x8f, 0xe0, 0x5b, 0x3e, 0xcb, 0x10, 0x31, 0x57, 0x18, 0x80, 0x53, 0xb9,
	0xb3, 0x00, 0x11, 0x33, 0xcf, 0xe4, 0xaf, 0x07, 0xfe, 0x4c, 0xec, 0x15, 0xe1, 0x47, 0x08, 0x79,
	0x51, 0x48, 0x52, 0xca, 0x7e, 0x68, 0x98, 0x3d, 0xa4, 0x57, 0x9b, 0xd2, 0x6f, 0x6e, 0xc4, 0xce,
	0x1a, 0x73, 0xa0, 0x6b, 0x92, 0x2b, 0xf0, 0x1d, 0xbc, 0x2a, 0xf8, 0x51, 0xe5, 0xa2, 0xc9, 0x6b,
	0x2e, 0xff, 0x90, 0x6e, 0xcd, 0xba, 0x33, 0xdd, 0x79, 0xf3, 0xd3, 0xf6, 0x6e, 0xb8, 0xfa, 0xb7,
	0x5c, 0x4b, 0x08, 0xdb, 0x53, 0xf8, 0x04, 0x81, 0xd2, 0x92, 0x48, 0xb7, 0x60, 0x6d, 0x85, 0x9f,
	0xcc, 0xb6, 0x43, 0xb7, 0xc7, 0x87, 0xd9, 0x63, 0xf7, 0x4f, 0xcf, 0xb6, 0xb0, 0x8b, 0x2a, 0xf9,
	0x02, 0x21, 0x23, 0xb5, 0xaf, 0xb4, 0xc2, 0xf7, 0x10, 0x6c, 0x0d, 0xae, 0x81, 0xec, 0x8d, 0x87,
	0xd9, 0xa8, 0xbb, 0x6a, 0x8d, 0x60, 0xad, 0x20, 0x9b, 0x41, 0x27, 0x27, 0xf8, 0x15, 0xa2, 0x69,
	0xd9, 0x14, 0xce, 0xab, 0xa7, 0xee, 0xd6, 0x35, 0x3d, 0x6f, 0x6e, 0x2c, 0x6b, 0x4f, 0x26, 0x2f,
	0x26, 0x77, 0xbf, 0xc0, 0x84, 0xd0, 0x65, 0x70, 0x15, 0xd8, 0x10, 0x7e, 0xfe, 0x1f, 0x00, 0x00,
	0xff, 0xff, 0x77, 0xd2, 0x4c, 0x02, 0x99, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RealEstateClient is the client API for RealEstate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RealEstateClient interface {
	FindHouse(ctx context.Context, in *Parameters, opts ...grpc.CallOption) (*Results, error)
}

type realEstateClient struct {
	cc *grpc.ClientConn
}

func NewRealEstateClient(cc *grpc.ClientConn) RealEstateClient {
	return &realEstateClient{cc}
}

func (c *realEstateClient) FindHouse(ctx context.Context, in *Parameters, opts ...grpc.CallOption) (*Results, error) {
	out := new(Results)
	err := c.cc.Invoke(ctx, "/RealEstate.RealEstate/FindHouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RealEstateServer is the server API for RealEstate service.
type RealEstateServer interface {
	FindHouse(context.Context, *Parameters) (*Results, error)
}

// UnimplementedRealEstateServer can be embedded to have forward compatible implementations.
type UnimplementedRealEstateServer struct {
}

func (*UnimplementedRealEstateServer) FindHouse(ctx context.Context, req *Parameters) (*Results, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindHouse not implemented")
}

func RegisterRealEstateServer(s *grpc.Server, srv RealEstateServer) {
	s.RegisterService(&_RealEstate_serviceDesc, srv)
}

func _RealEstate_FindHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealEstateServer).FindHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RealEstate.RealEstate/FindHouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealEstateServer).FindHouse(ctx, req.(*Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

var _RealEstate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RealEstate.RealEstate",
	HandlerType: (*RealEstateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindHouse",
			Handler:    _RealEstate_FindHouse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "real_estate.proto",
}
